version: 2
updates:
- package-ecosystem: docker
  directory: "/docker/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10

- package-ecosystem: bundler
  directory: "/docker/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
