global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: vmpooler-api
    metrics_path: /prometheus
    static_configs:
      - targets: ['vmpooler-api:4567']

  - job_name: vmpooler-manager
    metrics_path: /prometheus
    static_configs:
      - targets: ['vmpooler-manager:4567']
