{{- if .Values.ingress.enabled -}}
{{- $fullName := include "vmpooler.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vmpooler.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: '{{ .Values.vmpoolerInstance }}.{{ .Values.ingress.domain }}'
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-api
              servicePort: {{ $svcPort }}
            path: /
  {{ if .Values.ingress.useTLS -}}
  tls:
    - hosts:
        - '{{ .Values.vmpoolerInstance }}.{{ .Values.ingress.domain }}'
      secretName: '{{ .Values.vmpoolerInstance }}.{{ .Values.ingress.domain }}-tls'
  {{- end }}
{{- end }}
